# Generated by Django 2.1.5 on 2020-04-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200411_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
