# Generated by Django 2.1.5 on 2020-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200411_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
