# Generated by Django 2.1.5 on 2020-04-11 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200411_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Topic'),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Topic'),
        ),
    ]
