# Generated by Django 2.0.6 on 2020-03-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditentry',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
