# Generated by Django 2.0.6 on 2020-03-28 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200328_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditentry',
            old_name='login_time',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='auditentry',
            old_name='logout_time',
            new_name='logout',
        ),
    ]
