# Generated by Django 2.0.6 on 2020-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='longtitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
