# Generated by Django 2.0.6 on 2020-04-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_auto_20200329_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
