# Generated by Django 2.0.6 on 2020-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_auto_20200406_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
