# Generated by Django 2.1.5 on 2020-04-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_auto_20200412_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
