# Generated by Django 2.1.5 on 2020-04-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0008_auto_20200417_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
