# Generated by Django 2.1.5 on 2020-05-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_auto_20200417_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='signalpower',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
