# Generated by Django 2.0.6 on 2020-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_auto_20200417_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('taskid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
