# Generated by Django 2.1.5 on 2020-05-15 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_auto_20200514_1543'),
        ('subscribers', '0010_location'),
    ]

    operations = [
    ]
