# Generated by Django 2.1.5 on 2020-05-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0011_merge_20200515_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='tasktype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
