# Generated by Django 2.2 on 2020-05-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0012_location_tasktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='tasktype',
        ),
    ]
