# Generated by Django 2.2 on 2020-05-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0013_remove_location_tasktype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='slug',
        ),
    ]
